# Generated by Django 5.2.16 on 2026-07-29 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the educational module', max_length=200)),
                ('subject', models.CharField(help_text='Academic discipline category (e.g., Mathematics, Physics, English)', max_length=100)),
                ('grade', models.CharField(help_text='Target student grade level (e.g., Grade 6, Grade 8)', max_length=50)),
                ('duration', models.CharField(default='45 min', help_text='Estimated delivery or study time', max_length=50)),
                ('summary', models.TextField(help_text='Detailed overview of learning objectives and key topics covered')),
                ('thumbnail', models.URLField(help_text='Cover image asset URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_role', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('status', models.CharField(default='Success', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Unique identifier for portal login', max_length=50, unique=True)),
                ('password', models.CharField(default='teacher123', help_text='Hashed or plain password for demo authentication', max_length=128)),
                ('name', models.CharField(help_text='Full display name of the educator', max_length=100)),
                ('email', models.EmailField(help_text='Official contact email address', max_length=254, unique=True)),
                ('school_region', models.CharField(help_text='Assigned school district or geographic community region', max_length=100)),
                ('subject_specialty', models.CharField(help_text='Primary domain expertise (e.g., Mathematics, Science)', max_length=100)),
                ('joined_date', models.DateField(default=django.utils.timezone.now, help_text='Date educator joined the NGO learning network')),
                ('avatar', models.URLField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200', help_text='URL to profile avatar image')),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Teacher', help_text='System access privilege role', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource display title', max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video Lecture'), ('pdf', 'PDF Worksheet / Guide'), ('quiz', 'Interactive Quiz'), ('interactive', 'Slide Deck / Presentation')], default='video', max_length=20)),
                ('url', models.URLField(help_text='Direct link to hosted video, PDF document, or interactive media')),
                ('description', models.TextField(blank=True, help_text='Instructions or summary for this content item')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display sequence order within the lesson')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='portal.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Status flag indicating full lesson completion')),
                ('completed_content_ids', models.JSONField(blank=True, default=list, help_text='List of completed content item IDs')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='portal.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'lesson')},
            },
        ),
    ]
