# Generated by Django 5.2.16 on 2026-07-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the partner school', max_length=200)),
                ('location', models.CharField(help_text='District, region, or state', max_length=150)),
                ('logo_url', models.URLField(default='https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=200', help_text='URL to school logo or photo')),
                ('students_impacted', models.CharField(default='300+ Students', help_text='e.g. 450+ Students', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief summary of collaboration or school background')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display on the public landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Full name of reviewer', max_length=100)),
                ('author_role', models.CharField(help_text='Designation/Role, e.g. Grade 8 Science Educator', max_length=100)),
                ('school_name', models.CharField(blank=True, help_text='Associated school or district', max_length=150)),
                ('author_avatar', models.URLField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200', help_text='URL to avatar photo')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Star rating out of 5')),
                ('content', models.TextField(help_text='Detailed review or quote from the educator')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display in the landing page carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
